version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVICE_ADDRESS: 0.0.0.0
      SERVICE_PORT: 8080

      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_BROKER: "zookeeper:2181"
      KAFKA_TASK_TOPIC: "main_topic"
      KAFKA_GROUP_ID: "main_service"
      KAFKA_CONSUMER_TIMEOUT: 10000
    depends_on:
      - kafka
    ports:
      - "8080:8080"

  kafka:
    image: bitnami/kafka:3.2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"